### PR TITLE
Have more flexible server config.

### LINKED ISSUE #296: Improve git server configuration.
Right now there is some configuration in civet/settings.py for each type of git serrver (github, gitlab, bitbucket) but it is a bit clunky and doesn't generalize to using more than one server of a certain type. For example, there is no way to listen to events on both hpcgitlab.inl.gov ang gitlab.com.

Also, some of the settings should be specific to a particular server and/or repo.
Maybe something like:

```
GITHUB = {"url": "http://github.com",
    "oauth_client_id": "...",
    "oauth_secret": "...",
    ...
}
...

INSTALLED_GITSERVERS = [GITHUB, BITBUCKET, HPC_GITLAB, GITLAB]
```

### PR DESCRIPTION
**Pull request by brianmoose**
Allow more than 1 server of a given API type.
This is a breaking change to current OAuth
apps, the callback URL will need to include
the hostname.

closes #296

### CODE REVIEW

**Comment by brianmoose** [comment]
@pbauman Just a heads up, I don't know how often you update civet, but this PR breaks some server configuration. You will need to update `civet/settings.py`. Hopefully it will be clear what you need to change but if you have any questions, let me know.
Also, your OAuth Application callback URL will need to be updated. For example, for moose it was:
`https://www.moosebuild.org/github/callback/`
and changed to:
`https://www.moosebuild.org/github/callback/github.com/`

I have updated the [wiki](https://www.github.com/idaholab/civet/wiki) to reflect these changes but let me know if there is any confusion.

**Comment by pbauman** [comment]
Thanks for the heads up! I usually only update it when my server has to be rebooted because of a kernel upgrade, or more nefarious things like power outages. But, given this change, I'll update it later today and let you know if I hit any snags.

**Comment by pbauman** [comment]
OK, 1 snag. So I updated and I believe I followed all the instructions, but I guess I missed something. So I was able to successfully pulled from origin. I didn't look like I needed to actually change anything in settings.py from what I'd had before, am I mistaken? Anyway, I updated the callback link the OAuth app on Github. I restarted the server and the client. The client picked up the jobs, the website is up, but when I try to "sign in" on the website, it takes me to their 404 page. So I can't sign in to the CIVET site. Any help is greatly appreciated.

**Comment by pbauman** [comment]
Note I didn't change any of the webhook links on the GitHub repo pages, just the callback link in my settings for the OAuth application.

**Comment by pbauman** [comment]
Hmmm, it also looks like status updates aren't being pushed back to GitHub correctly CIVET. GitHub PR is showing "waiting" on the jobs to run, but CIVET server is showing them completed.

**Comment by pbauman** [comment]
Just a little more information, it looks like CIVET is receiving requests from GitHub OK. I just submitted a new PR to my repo and CIVET picked it up. But the GitHub PR is not showing the usual window with the testing results, as though CIVET is not there.

**Comment by brianmoose** [comment]
You probably won't have to change much in `civet/settings.py` but it sounds like you will need
to change the "remote_update" value from False to True. It needs to be True for status updates to actually go to github (the default settings are setup for testing where we don't want that).

As far as the sign in problem, can you go directly to the callback URL? It should give you the home page with a message that you failed to sign in. Is there anything in the logs?

**Comment by brianmoose** [comment]
For the sign in problem, you will also need to put your "secret_id" and "client_id" from your OAuth app into the github config dictionary. All the settings were moved from GITHUB_* to a python dictionary. So if you didn't change anything when you updated, your old settings aren't being used.

**Comment by pbauman** [comment]
> All the settings were moved from GITHUB_* to a python dictionary. So if you didn't change anything when you updated, your old settings aren't being used.

AH! That wasn't clear to me. I see now those options that were moved. I updated the dictionary according to my old options and restarted the server and everything is now working as expected. Thanks for responding before the holiday and Merry Christmas!

**Pull request merged**
